// nero-ui/src/components/media/SeriesCard.tsx
import type { Series } from "@nero/plugin-extensions";
import { A } from "@solidjs/router";
import { Show } from "solid-js";

export default function SeriesCard(props: { series: Series }) {
  return (
    <A
      class="flex flex-col gap-1 rounded-md p-1 duration-300 hover:bg-gray-200
        active:scale-95"
      href={`/series/${props.series.id}`}
    >
      <Show
        when={props.series.posterUrl}
        fallback={<div class="aspect-2/3 rounded-lg bg-gray-200" />}
      >
        <img
          class="aspect-2/3 rounded-lg object-cover"
          src={props.series.posterUrl}
          alt={props.series.title}
        />
      </Show>
      <h3 class="truncate text-center text-sm font-medium">
        {props.series.title}
      </h3>
    </A>
  );
}

// nero-ui/src/components/SeriesCard.svelte
<script lang="ts">
  import { link } from "./Router.svelte";
  import type { Series } from "@nero/plugin-extensions";

  let { series }: { series: Series } = $props();
</script>

<a
  class="flex flex-col gap-1 rounded-md p-1 duration-300 hover:bg-gray-200
    active:scale-95"
  href="/series/{series.id}"
  use:link
>
  <!-- TODO: Handle missing poster -->
  <img
    class="aspect-2/3 rounded-lg object-cover"
    src={series.posterUrl!}
    alt={series.title}
  />
  <h3 class="truncate text-center text-sm font-medium">{series.title}</h3>
</a>
