// nero-ui/src/App.tsx
import ExtensionGuardLayout from "./layouts/ExtensionGuardLayout";
import Layout from "./layouts/Layout";
import SettingsLayout from "./layouts/SettingsLayout";
import AppSettingsPage from "./pages/AppSettingsPage";
import ExtensionsSettingsPage from "./pages/ExtensionsSettingsPage";
import HomePage from "./pages/HomePage";
import SearchPage from "./pages/SearchPage";
import SeriesPage from "./pages/SeriesPage";
import { Navigate, Route, Router } from "@solidjs/router";

export default function App() {
  return (
    <Router root={Layout}>
      <Route path="/" component={HomePage} />

      <Route path="/" component={ExtensionGuardLayout}>
        <Route path="/search" component={SearchPage} />
        <Route path="/series/:seriesId" component={SeriesPage} />
      </Route>

      <Route path="/settings" component={SettingsLayout}>
        <Route path="/" component={() => <Navigate href="/settings/app" />} />

        <Route path="/app" component={AppSettingsPage} />
        <Route path="/extensions" component={ExtensionsSettingsPage} />
      </Route>
    </Router>
  );
}

// nero-ui/src/App.svelte
<script lang="ts">
  import Router from "./components/Router.svelte";
  import Layout from "./layouts/Layout.svelte";
  import HomePage from "./pages/HomePage.svelte";
  import SearchPage from "./pages/SearchPage.svelte";
  import SeriesPage from "./pages/SeriesPage.svelte";
  import SettingsPage from "./pages/SettingsPage.svelte";

  const routes = {
    "/": HomePage,
    "/search": SearchPage,
    "/series/:seriesId": SeriesPage,
    "/settings/:section?": SettingsPage,
  };
</script>

<Layout>
  <Router {routes} />
</Layout>
